"""Add ingredients column to Pizza

Revision ID: 27c88f0609d7
Revises: fae109f76fcc
Create Date: 2025-06-17 10:54:15.804974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c88f0609d7'
down_revision = 'fae109f76fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.String(), nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
